baseURL: "https://arishoham.com"
languageCode: "en-us"
title: "Ari Shoham"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "This is a test"

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Ari Shoham"
  namecolor: ffc107
  profession: "Engineer"
  github: "https://github.com/arishoham"
  # gitlab: "https://gitlab.com"
  linkedin: "https://linkedin.com/arishoham"
  twitter: "https://twitter.com/arishoham"
  instagram: "https://instagram.com/arishoham"
  facebook: "https://facebook.com/arishoham"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Ari Shoham, a passionate Engineer. I like to solve problems."
  descripe_l2_person: "You can find my works [here](#projects)"
  skills:
    - name: Javascript
      percentage: 90
    - name: HTML
      percentage: 85
    - name: CSS
      percentage: 80
    - name: Friendliness
      percentage: 75

  # Experience
  disable_experience: false
  experience:
    - company: "STRATUS Simulation Center"
      # id: "Stratus"   // use this, when you want to change the id(used for navigation)
      role: "Simulation Specialist"
      startdate: Nov 2020
      enddate: present
      featuredpoints:
        - point: Organize and run medical simulation.
        - point: Build and implement complex training models. 
    - company: "Hagen Company"
      # id: "Hagen-and-company" // use this, when you want to change the id(used for navigation)
      role: "Engineering and management Consultant"
      startdate: Dec 2019
      enddate: Jun 2020
      featuredpoints:
        - point: Coordinated a 10-35% increase in productivity.
        - point: Led and motivated multi-disciplinary teams in manufacturing.
    - company: "BMW Manufacturing"
      # id: "Bmw" // use this, when you want to change the id(used for navigation)
      role: "Implementation engineer"
      startdate: Aug 2016
      enddate: May 2018
      featuredpoints:
        - point: Defined requirements for steering wheel vibration measurements.
        - point: Developed VBA programs to automate processes.

  # Education
  disable_education: false
  education:
    - degree: "Bachelor"
      branch: "Mechanical Engineering"
      university: "Clemson"
      startedyear: "2014"
      graduation: "2019"
    # - degree: "Degree"
    #   branch: "Branch"
    #   university: "Example university"
    #   startedyear: "year"
    #   graduation: "year"
    # - degree: "Degree"
    #   branch: "Branch"
    #   university: "Example university"
    #   startedyear: "year"
    #   graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "arishoham@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: false
